import { EnumPeriod } from "../TLEvent";

export interface InterfaceAddPeriodView {
  ShowDialog(): void;
  SetName(value: string): void;
  SetIsPeriod(value: boolean): void;
  SetBeginType(value: EnumPeriod): void;
  SetBeginDayDay(value: number): void;
  SetBeginDayMonth(value: number): void;
  SetBeginDayYear(value: number): void;
  SetBeginMonthMonth(value: number): void;
  SetBeginMonthYear(value: number): void;
  SetBeginYear(value: number): void;
  SetBeginDecadeDecade(value: number): void;
  SetBeginDecadeCentury(value: number): void;
  SetBeginCentury(value: number): void;
  SetEndType(value: EnumPeriod): void;
  SetEndDayDay(value: number): void;
  SetEndDayMonth(value: number): void;
  SetEndDayYear(value: number): void;
  SetEndMonthMonth(value: number): void;
  SetEndMonthYear(value: number): void;
  SetEndYear(value: number): void;
  SetEndDecadeDecade(value: number): void;
  SetEndDecadeCentury(value: number): void;
  SetEndCentury(value: number): void;
  SetError(err: string): void;
  GetName(): string;
  GetIsPeriod(): boolean;
  GetBeginType(): EnumPeriod;
  GetBeginDayDay(): number;
  GetBeginDayMonth(): number;
  GetBeginDayYear(): number;
  GetBeginMonthMonth(): number;
  GetBeginMonthYear(): number;
  GetBeginYear(): number;
  GetBeginDecadeDecade(): number;
  GetBeginDecadeCentury(): number;
  GetBeginCentury(): number;
  GetEndType(): EnumPeriod;
  GetEndDayDay(): number;
  GetEndDayMonth(): number;
  GetEndDayYear(): number;
  GetEndMonthMonth(): number;
  GetEndMonthYear(): number;
  GetEndYear(): number;
  GetEndDecadeDecade(): number;
  GetEndDecadeCentury(): number;
  GetEndCentury(): number;
}